site_name: WMO ET-ACDM
site_description: ET-WDC workspace collaborating on issues of data management, data access, metadata handling and exchange, data archiving and links to WIGOS and the WMO Information System (WIS).
site_author: WMO Expert Team on World Data Centres (ET-WDC)
copyright: Copyright (c) 2006 - 2019 WMO Expert Team on World Data Centres (ET-WDC)
site_url: https://wmo-im.github.io/et-acdm
repo_url: https://github.com/wmo-im/et-acdm/
docs_dir: docs

nav:
    - Home: index.md
    - The Team: team.md
    - Meetings:
      - 2006: meetings/2006/index.md
      - 2007: meetings/2007/index.md
      - 2008: meetings/2008/index.md
      - 2009: meetings/2009/index.md
      - 2010: meetings/2010/index.md
      - 2011: meetings/2011/index.md
      - 2012: meetings/2012/index.md
      - 2014: meetings/2014/index.md
      - 2015: meetings/2015/index.md
      - 2016: meetings/2016/index.md
      - 2017: meetings/2017/index.md
      - 2018: meetings/2018/index.md
      - 2019: meetings/2019/index.md
      - 2020: https://github.com/wmo-im/et-acdm/wiki/Meetings#2020
      - more...: https://github.com/wmo-im/et-acdm/wiki/Meetings
    - Terms of Reference: terms-of-reference.md

theme: flatly

edit_uri: edit/master/website/docs

extra_css:
    - css/et-acdm.css

plugins:
    - search
